### ISSUE TITLE
Volunteers Page: After Gifts have been Redeemed: Return Item

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#100]
Bug: Does not appear there is a way to return an item in any mode. (For reference, this does happen if a member wants to swap a size in t-shirts.)

**Comment by AricStewart** [comment]
It was not in the original spec to allow returns. I see why it would be needed. I can work on this functionality.

**Comment by AricStewart** [comment]
Should be fixed, reopen if not.
