### ISSUE TITLE
Main Page and Volunteers Page: Volunteer Hours Information Fields

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#101]
User Interface: Have the following information fields pop out more and appear at the top of the Main page and the Volunteers Page: 

   Total Hours
   Hours Spent
   Hours Remaining

These are the fields that are most relevant to the Volunteers Department and the members. The details are still wanted/needed, but this information should be more easily found and identifiable.

**Comment by AricStewart** [comment]
Makes sense I can claim this modification

**Comment by AricStewart** [comment]
Question!  Are those for the whole con or for the individual user?

**Comment by lmhern1** [comment]
Both. 

When a member logs, it would be preferred that their personal "totals" would appear first and the details would be documented further. 

On the Volunteers Page, the totals for everything or what they are looking up would appear first with the details appearing later. 

Right now both appear towards the end of the detail lists, instead looking for an area or box to appear at the top of the page with the totals and details to appear later. For example, on the Volunteer Management Page, the Totals bar appears in middle of the screen, the request would be to move this to the top of the screen.

**Comment by lmhern1** [comment]
Rough example of what I was thinking for the member's main page- to clarify, Volunteer Hour Information would be at the top of the Volunteer Section on the Main Page. (I don't want to mess with Thomas' master plan for the layout of the Main Page.)

![member](https://user-images.githubusercontent.com/37823973/37991807-a970347e-31f9-11e8-95d3-c705dcb1050d.PNG)

**Comment by AricStewart** [comment]
Please retest with new release, re-open if failure remains.
