### ISSUE TITLE
Volunteer Hours: Decimal Readability Update

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#102]
User Interface: Take off unnecessary decimal points in hour calculations.

**Comment by AricStewart** [comment]
Should it be reported in minutes then?  XXX Hours YYY Minutes? 
Are all prizes in whole hours? Otherwise it gets weird to determine if a given person is eligible.

**Comment by lmhern1** [comment]
XXX Hours YY Minutes
All gifts are in whole hours

**Comment by seanbseanb** [comment]
Do fractional hours make more sense?  7.5 hours?

**Comment by AricStewart** [comment]
Currently it is decimal.

<img width="840" alt="screen shot 2018-03-27 at 11 41 31 am" src="https://user-images.githubusercontent.com/1994679/37981657-e474fb5e-31b3-11e8-8869-d6ae091be2e6.png">

Here is with Hour... Min...

<img width="840" alt="screen shot 2018-03-27 at 11 40 38 am" src="https://user-images.githubusercontent.com/1994679/37981653-e15c4346-31b3-11e8-8e9b-c57d3c0d579d.png">


Please excuse the funky minutes remaining that is because of the way test data is generated.

**Comment by lmhern1** [comment]
Ideally, there would not be any trailing zeros.  

So, we would only see the following (for example, in Actual Hours Column): 

X  or X.0 
X.25
X.5
X.75

With the minutes being rounded, these are the only outputs that we should see for the calculated hours (and hours remaining).

**Comment by AricStewart** [comment]
Ok so no "Hour XX Minute YY" You just want 2 decimal points preferably only on the quarter hours? 

I am now confused.

**Comment by lmhern1** [comment]
OK, So I think I understand the confusion. 

When talking about the total outputs, Hour XX Minute YY is fine. 

The decimal readability is referencing the "listing" of hours, such as in your screen shot, the Actual Hours listed and in the Volunteers Page the Total Hours. Since all time will be rounded, the only outputs in the "minutes" section of calculated hours should be X.0, X.25, X.5, and X.75. 

![here](https://user-images.githubusercontent.com/37823973/37990438-d20568ae-31f5-11e8-9dca-008b47ed0109.PNG)

**Comment by lmhern1** [comment]
In other words, as long as the rounding is functioning correctly, that will be the output, the readability is to eliminate the unnecessary trailing zeros (so X.5 not X.50).

**Comment by AricStewart** [comment]
Understood.  Got-it!

**Comment by AricStewart** [comment]
Please retest with new release, re-open if failure remains.
