### ISSUE TITLE
Enter Hours Page: Date/Time that the Shift Ended Field: Rounding Incorrect

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#117]
Sorry, didn't grab a screenshot. 

At 8:43PM the default time when going to the Enter Hours Page was 9:00PM. Should have defaulted to 8:45PM. 

Related to Issue #97 Enter Hours Page: Date/Time that the Shift Ended Field: 15 Minute Increments

**Comment by AricStewart** [comment]
You sure your clock is correct?  I have not seen this problem. I will pay more attention and see if I can reproduce it.

**Comment by lmhern1** [comment]
I'll try to grab a screenshot if I see it again. I tried at both 8:43 and 8:44PM

**Comment by AricStewart** [comment]
Ok I am seeing it at 9:04 also.

**Comment by tskeeley** [comment]
The server time is wrong.  I'll contact dreamhost and have it fixed.
