### ISSUE TITLE
Ability to hide contact information from records

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#150]
Need the ability to hide contact information from records. For example, for Guests of Honor.

**Comment by AricStewart** [comment]
Ok need a bit more information about this.

Lets start with hide the information where and from who?

-aric

**Comment by AricStewart** [comment]
I need more information on this or it is a unsolvable issue.  Please update with details.

**Comment by mshappe** [comment]
Closing this as far too vague.
