### ISSUE TITLE
Hours Calculation wrong on "Enter Hours" tab

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#157]
When selecting partial hours (:15, :30, :45) the "hours credited" reports those minutes as full hours of credit.  See attached screen shots for details.

![enterhours](https://user-images.githubusercontent.com/1123396/40957390-94112eca-685a-11e8-9c76-ebfbca2bc5d7.png)

**Comment by AricStewart** [comment]
Patch #158 should resolve this display only issue.

**Comment by tskeeley** [comment]
Looks solved!  Thanks!
