### ISSUE TITLE
Volunteers: Prizes to Gifts

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#168]
Need to have references of the Volunteer Prizes changed to gifts. 

The board about a year ago asked that we refer to the Volunteer prizes/swag as gifts. This has been a directive to change the perception of the gifts that we give volunteers for the time they spend volunteering for us. 

Although this is not critical to get done right away, I am already getting push back on our use of "prize" vs gift. 

For example:
<img width="1142" alt="screen shot 2018-06-09 at 7 47 08 pm" src="https://user-images.githubusercontent.com/37823973/41197284-f961dcfe-6c1d-11e8-858b-8b78127f50fb.png">

**Comment by AricStewart** [comment]
Ok doing just the user interface is pretty straight forward.  If they are going to complain about the codebase then it will be a bit more of a project.

**Comment by lmhern1** [comment]
Yes, just user interface. If we could get it updated on the Volunteers Page (Add New Prize) that would be great. 
Thank you!
