### ISSUE TITLE
Bug: batch file upload: Volunteer CSV File To Upload- DateTime upload issue

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#179]
When using the format provided, using the quotes around the date/time does not work to keep it in text format. No error message given. 

However, if format is changed from text to date/time, it will upload but not in the correct format (date is wrong, sometimes date/hours are zeroed out).  No error message is given if the format is not correct.

**Comment by AricStewart** [comment]
"2018-06-05 08:15:00" They need to be straight quotes not smart quotes.   I think the PHP is automatically changing the example.

“2018-06-05 08:15:00” is bad "2018-06-05 08:15:00" is good.

**Comment by AricStewart** [comment]
Also adding help text saying:
EndDateTime should be quoted. The format is "YYYY-MM-DD HH:MM:SS".

**Comment by AricStewart** [comment]
Imhern1, Was this the issue or is there a more problematic issue? 
The examples and information should be more complete now. I have several test files here that appear work work without issue. 

If this is still and issue that we are missing please re-open the issue.
