### ISSUE TITLE
Volunteer Tracking

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#18]
I have tasks I want help with - but I need to know if anyone wants to work with this on me.  I can break these into individual issues if needed/wanted

Current needs:
- On volunteer page (volunteers), Search by name/email/memberID
- One Volunteer page (volunteers) AND member portal (main), display total, total available, total claimed numbers for hours.
- On Volunteer page (volunteers), add "picked up tshirt" box for claim, only available if member has volunteers a number of hours
- On Volunteer page (volunteers), add "picked up Thank You item" for exchanging hours for swag and updating the "total claimed" numbers (well, tracking that it was picked up, and supporting a calculation of total claimed during display)
- On entry page (volhours), add support for using the cell phone cam as a barcode reader to fill in memberID field. (there are a number of libraries out there to do this via a webpage)
- On entry page (volhours), remember last department used for hours credit, and prefill it
- On entry page (volhours), verify that volunteer isn't "overlapping" hours (might not be needed, or might need exceptions?  Need to verify with volunteer department)

Complete
- On entry page (volhours), add "search by email" option to look up a volunteer id if badge isn't available (eg: when not at con)

**Comment by AricStewart** [comment]
I am happy to take this up as a primary task if you want to help break them down. 

there are 2 pages (as in function=XXX) "volhours" and "volunteers" so lets be clear what goes where. I assume "entry page" -> "volhours" 

Right now the volunteer pages is very sparse. Do you have any mock ups of what you envision? 

I would imagine having a "my own hours" sort of display even for non ConCom/Admins would be nice for the average member as well.

**Comment by tskeeley** [comment]
Yes, Entry = volhours (updated task info)

Volunteer is only accessible if the user is in the volunteer department, so items on tht page are for them in volunteer maintenance. Things like tshirt pickup, volunteer hour checking, thankyou gift redemption...  I need a "search by email", display of all activity for a member by accountID, eventually a "correct entry" and then the "pick up" or "sell" routine to handle claiming items.  (and likely returning them too, since you know people will make mistakes or randomly change their minds)

"My own hours" would be something added to main (the dashboard) that anyone could see.  Display only if entries found.

**Comment by tskeeley** [comment]
Grab the items you want from these and make separate issues and assign yourself.  We can track and integrate that way!

**Comment by AricStewart** [comment]
I have this one done:

On entry page (volhours), add "search by email" option to look up a volunteer id if badge isn't available (eg: when not at con)

But it is dependent on my current outstanding pull request.

**Comment by tskeeley** [comment]
great!  Thank you.   I got the other one merged.

**Comment by AricStewart** [comment]
Whittling away at a few more of these.

 * On entry page (volhours), remember last department used for hours credit, and prefill it
 * On main display total hours

**Comment by AricStewart** [comment]
There is a lot of back end / Neon work for many of these items that I would like to kick up to a decision maker. 

- How do we track hours spent? A field in the back end somewhere
- How do we track t-shirts? <ditto>

For overlapping hours do we warn? forbid? what is the clear policy there?

**Comment by tskeeley** [comment]
I think the best option for hours spent is to have an object/table that only contains the items that a member picks up.  We can calculate the total hours/items on page load so that we know what people picked up or what they have left.  Good for future tracking (eg: trending of tshirt sizes, favorite kinds of gifts, etc.)  Just to make sure I'm not overlooking something obvious, let me ask if you are you okay with that idea?

As for tshirts - the condition is that someone has put in "X" number of hours (I think it's currently 15).  It doesn't matter if they have redeemed any or not.  The tshirt option shows after they collect the hours, and the shirt costs zero hours.  But we should track size picked up and make sure people only get one.  That will help us plan for future years.

Overlapping hours - I don't know that we have a policy yet.  Let's code for warn, with the option to forbid.  And forbid will likely need an option to override if they are admin or in the volunteer department.  The options and all can be a future option if needed.  And we can talk about it with Volunteers at the January ConCom.  So, for now, Warn would be good enough.  Does that sound logical to you, if so, let's make it so!

**Comment by AricStewart** [comment]
Ok quick assessment here:

The Following are now completed:

- **DONE** : On volunteer page (volunteers), Search by name/email/memberID  
- **DONE** :  On entry page (volhours), add support for using the cell phone cam as a barcode reader to fill in memberID field. (there are a number of libraries out there to do this via a webpage) 
- **DONE** : On entry page (volhours), remember last department used for hours credit, and prefill it
- **DONE** : On entry page (volhours), verify that volunteer isn't "overlapping" hours (might not be needed, or might need exceptions? Need to verify with volunteer department)

The Following are waiting on the database redesign: (Issue #27)

- On Volunteer page (volunteers), add "picked up Thank You item" for exchanging hours for swag and updating the "total claimed" numbers (well, tracking that it was picked up, and supporting a calculation of total claimed during display) 
- On Volunteer page (volunteers) AND member portal (main), display total, total available, total claimed numbers for hours.
- On Volunteer page (volunteers), add "picked up tshirt" box for claim, only available if member has volunteers a number of hours

**Comment by tskeeley** [comment]
Got it.  I'll get that complete.  Then, when this is done, we can take on
the reg system, I think.


-- Thomas

Any road followed precisely to its end leads precisely nowhere. Climb the
mountain just a little bit to test it's a mountain. From the top of the
mountain, you cannot see the mountain.
-- Frank Herbert

**Comment by AricStewart** [comment]
Awesomesauce. ;)

I am hoping we get the formal process started soon. I was expecting user stories, clear issues and direction flowing from Sean as per out meeting over a month ago.

**Comment by seanbseanb** [comment]
Yep, sorry guys.  Work has been pretty ugly.  I’ve got this on my short list, and we seem to have lost our project manager.  I’ll have some evening time later this week to put into this.

Do we think the Volunteer tracking work is complete?

**Comment by AricStewart** [comment]
Extensive testing will be required. I would not want this to be tested at the Con.  Meaning can we get mock badges with mock barcode for barcode reading?  Then test on mobile devices.

The database redesign will unlock the reward work that is yet to be done.

I would like an editing function maybe in the volunteer master page where conflicting hours are more highlighted and hours can be add/removed from there. But that is all just from my brain and having worked behind a table at a CON what facilities would make or break me being willing to use this system.

But otherwise volunteer stuff is coming along quite nicely.

**Comment by seanbseanb** [comment]
Under no circumstances will we be testing anything at CON.  Do you have a few minutes in the next couple days to take me through what’s been done so far?

**Comment by AricStewart** [comment]
e-mail? Phone? In Person? I am basically unavailable from Friday -> 26th. But have some time Wednesday and Thursday. Lets take this to e-mail as we are polluting this issue.

**Comment by tskeeley** [comment]
The Core Database code is merged to master.  This issue is clear to proceed again.

**Comment by AricStewart** [comment]
Update

The Following are now completed:

- DONE : On volunteer page (volunteers), Search by name/email/memberID
- DONE : On entry page (volhours), add support for using the cell phone cam as a barcode reader to fill in memberID field. (there are a number of libraries out there to do this via a webpage)
- DONE : On entry page (volhours), remember last department used for hours credit, and prefill it
- DONE : On entry page (volhours), verify that volunteer isn't "overlapping" hours (might not be needed, or might need exceptions? Need to verify with volunteer department)
- DONE: On Volunteer page (volunteers) AND member portal (main), display total, total available, total claimed numbers for hours

The Following are in process:

- On Volunteer page (volunteers), add "picked up Thank You item" for exchanging hours for swag and updating the "total claimed" numbers (well, tracking that it was picked up, and supporting a calculation of total claimed during display)
- On Volunteer page (volunteers), add "picked up tshirt" box for claim, only available if member has volunteers a number of hours

**Comment by AricStewart** [comment]
I believe all the tasks on this issue are now finished!
