### ISSUE TITLE
Volunteer Rewards Report- Need additional Column added to report

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#187]
The VolunteerRewards CSV report currently does not include the "remaining" inventory of the gifts. 

If we can get that information added to the report, that will make inventory easier to verify. 

![screen shot 2018-07-13 at 11 12 29 pm](https://user-images.githubusercontent.com/37823973/42720720-4ff9450e-86f2-11e8-97d2-78788b07466e.png)
<img width="774" alt="screen shot 2018-07-13 at 11 12 39 pm" src="https://user-images.githubusercontent.com/37823973/42720721-527ab092-86f2-11e8-8c81-e7444a252d13.png">

**Comment by AricStewart** [comment]
ok working on a solution for this.
