### ISSUE TITLE
VolunteerHours CSV Report: DepartmentID

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#188]
Is there a list of what Department ID goes with which department? 

I would like to begin deciphering the Volunteer Reports but I'm missing some information to make this easier. If I could get a list of Department ID that correspond to Department Names, that would be great. 

<img width="778" alt="screen shot 2018-07-13 at 11 19 43 pm" src="https://user-images.githubusercontent.com/37823973/42720773-7dfaae4c-86f3-11e8-9ec9-b9aae52680a5.png">

**Comment by AricStewart** [comment]
Attaching a list

[Departments.txt](https://github.com/CON-In-A-Box/CIAB-Signin/files/2195184/Departments.txt)

I will also add a way to generate a nicer output table that has these names included.
