### ISSUE TITLE
Volunteer Gift Redemption/Inventory: Items not appearing when inventory is 0

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#195]
When the inventory of a volunteer gift was down to 0, it would no longer appear nor could it be used to redeem gifts. This cause the Volunteer Department to create another listing of the gift, which caused confusing duplication in the output report at the end of the convention. 

Request to have the gift listed even if the inventory drops below 0. This often happens in both Volunteers and Merchandise as volunteers will sometime select the incorrect size, or a size is returned and has not been properly added back to the inventory.

**Comment by tskeeley** [comment]
This also implies we need a inventory true-up process (how to make the numbers in the portal reflect actual counts)  AND a "display item" option in the items that would be the actual decider of displaying an item or not.

**Comment by AricStewart** [comment]
The True Up stuff is there. You can modify the inventory count right now to try to true it up.

**Comment by AricStewart** [comment]
Note there is an option to "Show sold out Items"  This does exactly what they wanted. Show items with a quantity of 0. Should maybe that just be turned on by default and called "Hide sold out Items"?

**Comment by tskeeley** [comment]
Yes, flipping that default would work.
