### ISSUE TITLE
Move Events and meetings to Administration tab

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#212]
This is a site administration function and should not have it's own "department administration" tab

**Comment by tskeeley** [comment]
Suggestion - The administration page should likely be a launch point to other functions.  A menu page type thing?  That would also allow us to have modules insert admin functions (EG: the ConCom Structure tab from the concom list should be an admin function)

- Configuration
- Events and meetings
- Debug logs
- DB Lookup
- ConCom Structure
- etc

**Comment by AricStewart** [comment]
Here is a proposal where the Administer menu is a dropdown with the admin menus in it. 
Thoughts?

**Comment by tskeeley** [comment]
woops, something went wrong

Now documents and volunteers are in the menu as well.

**Comment by AricStewart** [comment]
Documents I am moving, Volunteers  is the admin page for volunteers.

We could add a new dropdown of "Department" and have it go there and also  have other conditional department pages appear there. 

Or move it out of the admin menu, or leave it. I see arguments for all 3 possibilities.
