### ISSUE TITLE
Documents need files

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#219]
The documents section should allow for folders/sub-folders.  Folder names are not static or pre-defined.

Example:
/portalroot
|
|- 2019 ConCom
|- 2018 ConCom
|- ConCom Archive
| |-
|- ConCom Common
|- How to brush a lama

**Comment by AricStewart** [comment]
This  brings up some important design questions.

1) Do you want to load the whole directory structure on initial load and have a tree view sort of control?  For small directory trees  this will be fast and easy to navigate. However if the total  documents gets really large then it start to take a long time to load everything and that becomes a problem. 

2) Do you want the UI to be browsing based where when you click on folders they somehow refresh the web page with that folders contents? We would likely need '..' or 'parent folder' or something similar as links as well to allow back up the folder tree.   This should have faster initial load times but then you have additional  load times with each tree navigation up and down. Also an easier time getting "lost" 

3) something else? Maybe a tree view that populates branches on first open? 

I think I vote #2 honestly.  Though I do not think it would be the easiest to use I think it is likely to be the most robust.

**Comment by tskeeley** [comment]
I agree with you and also prefer #2, with a link "jump to top folder" so people don't get lost.
