### ISSUE TITLE
Some mobile users are unable to authenticate

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#238]
Some users are unable to authenticate on mobile, even though the same credentials work fine on Chrome on Mac OSX (as tested by Sean).

Cleaning cache on browser seems to help.

Could pragma no-cache help us here?

https://stackoverflow.com/questions/10314174/difference-between-pragma-and-cache-control-headers

Need to figure out what's really going on, root cause, etc. etc.

**Comment by AricStewart** [comment]
So to be clear, clearing the cace on the browser on the mobile device allows login?
 Yet likely we would want to set no-cache. 
Patch pending.

**Comment by AricStewart** [comment]
The change is in place.
Sean any chance you can test this?

**Comment by AricStewart** [comment]
Waiting for review! If no response will close as fixed and working. As far as I know it should be.

**Comment by mshappe** [comment]
The only thing I've seen that relates to this at all is the case-sensitivity thing, which A] is another ticket and B] may not actually be the problem there either. But I think we can call this closed.
