### ISSUE TITLE
Discount Codes vs. multiple ticket prices

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#240]
As evidenced by setting up the Dealer's & Artist's Alley events this year (and previous), we are asked every year to: 

- create several pricing levels for Dealer's tables, 
- provide a specific, exclusive link to register for that event (may be a NeonCRM artifact), and then 
- be able to turn registration for that event on and off on short notice

The pricing levels will usually change after the Jan 15 price increase, but this is more nice to have.

**Comment by AricStewart** [comment]
Are these separate events, not the CON? 
Are they general registration of invite only?
Are there tickets involved or just dealer/artist things.

We do not presently have any support for dealer's tables or anything of the like it is future functionality that we have been told is not a priority at this time.

**Comment by mshappe** [comment]
Clarifying this and then closing it to be succeeded by future requirements work:

Because we do track dealers tables in Neon, we will need to do so in our New Registration Module.

We do not need to do so in CIAB right now except if it can be done as precursor work to New Reg.
