### ISSUE TITLE
Registration Worker: Guest Lookup

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#253]
Registration Workers should be able to look up guest registrations by last name, email address , or badge number.

**Comment by seanbseanb** [comment]
I believe last name/first name is already closed, pending review.

**Comment by AricStewart** [comment]
Any of the lookup bars should respond to full names (Real or preferred) , email and badge number

https://ciab.anergyst.org/index.php?Function=registration

If you need to be able to look someone up by JUST last name I can add that facility.

**Comment by AricStewart** [comment]
Please test the functionality.

**Comment by AricStewart** [comment]
Check it out again please.. updated:
https://ciab.anergyst.org/index.php?Function=registration&memberId=1231

**Comment by mshappe** [comment]
What is the current status of this issue?

**Comment by AricStewart** [comment]
I believe this is complete and just was waiting on official testing/closing.

**Comment by AricStewart** [comment]
I am going to poke this one last time and then just close it as fixed and inactive.

**Comment by mshappe** [comment]
This appears to work as intended.
