### ISSUE TITLE
Supportability: Understanding deployed versions

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#261]
When looking at the front page of CIAB, there should be a version number findable within either the source, or in an unobtrusive place on the screen.  In other products, this is sometimes shown with a full “Version: 1.2.3.4” tag in clear text, in other products it has been either hidden in the page source, or shown as white-on-white text (which can then be shown by “select-all” on the main page.

**Comment by AricStewart** [comment]
This issue is now resolved.
