### ISSUE TITLE
Duplicate Logins that Aren't Actually Duplicate Accounts

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#267]
JP bought a guest-of badge this morning (at con) for someone. Now, when he logs into Signin, it gives him the warning about having two accounts. Except he doesn't: he has one ACCOUNT and two badges associated with his name (his own, and the guest of, which has actually been assigned since to its actual holder).

We should be smarter when we interact with Neon to only flag duplication where it's truly a duplicate login. If it's a single person with multiple badge numbers associated with them, then we should treat it that way and show them all the badges they've been associated with.

Since NEON makes this distinction, we should be able to.

I can demonstrate visually on request.

**Comment by AricStewart** [comment]
Please Note! This is a fundamental design change!

The original design was 1 badge = 1 account (email)  and 1 account (email) = 1 badge. That was what all the tables and system was designed around. 

This change was not made because it  has not been spelled out very well. And the work that was done was around dependent accounts as issue around guess of badges never came up either.

We can make changes but they need to be designed and thought through.

**Comment by mshappe** [comment]
No argument about that -- this appears to have been a change within Neon and not one we would have asked for (if only because we weren't ready for it). 

It does fit in with what we've discussed in terms of our own registration system, where "person", "badge" and "login credentials" are three orthogonal ideas (and none of them are ever again called "account" which is far too vague), but we were not prepared for Neon to change its behaviour on us.

**Comment by tskeeley** [comment]
Yes, this is a neon change, and not one we should support.  We need to maintain the 1:1 relationship.  Also, as we are ending guest of (in favor of gift card) we should not put a design change into this.  (my $0.02, assuming I understand the 'glitch')

Long and short of this, and everyone already knows - we need OUT of neon asap.  OF course, the right time to talk about that is NOT right now as we are working to get clear of the hotel.

**Comment by mshappe** [comment]
Labeling `wontfix` and closing.
