### ISSUE TITLE
Usernames should not be case-sensitive

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#270]
I had a user come to me today who was having trouble getting password reset or logging on. Turned out her mobile device was auto-capitalizing the first letter of her email address, and we were matching case-sensitive, and it was saved all-lowercase.

If at all possible, usernames should be case-insensitive.

This may be related to #238

**Comment by AricStewart** [comment]
We sure all the e-mails are lower case? Right now in Neon we don't have any information about that.  I can make the input all forced to lower but that could cause complications.  If you feel like the neon database is all lower case then it is relatively easy change.

**Comment by AricStewart** [comment]
Ok I do not believe this is the problem because I can log into https://signin.convergence-con.org with aricstewart@gmail.com, Aricstewart@gmail.com and aricStewart@gmail.com without issue. So the login e-mail is not being matched case sensitive.

**Comment by AricStewart** [comment]
@mshappe I do not think this issue is correct. I believe it is invalid.
Could you retest and prove me wrong.

**Comment by mshappe** [comment]
Cannot reproduce. Closing.
