### ISSUE TITLE
Login to signin.convergence-con.org with expired password broken

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#286]
Signing in returns immediately to the login page.

**Comment by AricStewart** [comment]
This is because a whole slew if people had their authentication expire 9/1/2019  and our prompt to change your password is evidently broken. 

Emergency averted (pushed expiration date out)

Editing this issue to reflect the bug that needs fixed.

**Comment by mshappe** [comment]
#287
