### ISSUE TITLE
Portal: Deleting a department should "delete" its membership

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#303]
Instead of preventing deleting a department if it has membership, deleting should simply flag all memberships as "ended" (#302), and then the department should also be deleted (or similarly soft-deleted/hidden).

**Comment by AricStewart** [comment]
Test and confirm please

**Comment by mshappe** [comment]
Deleting Dock (which is in fact supposed to go away) failed with a 500
error.

**Comment by AricStewart** [comment]
Correction made, please try again.

**Comment by mshappe** [comment]
This now appears to work! Yay!
