### ISSUE TITLE
Portal: Historical Staff counted against current department numbers

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#308]
Historical staff are still counted in departments and will block department deletion (because the count is non-0). 

Semi-related to #302, #303 but those are more future-state.

**Comment by AricStewart** [comment]
Test and confirm please

**Comment by mshappe** [comment]
Future Visioining now correctly shows up with 0 members.

**Comment by AricStewart** [comment]
Closing
