### ISSUE TITLE
Table 'VolunteerRewards' does not have YearID

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Signin#44]
Is this intended?  Aren't prizes based on years also?

**Comment by AricStewart** [comment]
Thinking about this a year is not required huh.  Rewards are not removed because the year is up, they keep being available to give away until they are gone.

I am going to let you close this one to confirm but I believe I have figured it out correctly...

**Comment by tskeeley** [comment]
you are correct.  We continue to have/offer things.
