### ISSUE TITLE
Volunteer's administrative portal

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Signin#49]
Please review feature proposal, Please edit, rank, discard as appropriate.

Likely volunteer heads/managers are going to need to be able to administrate volunteer data such as inventory correction, hour corrections and the like.  It would be good to give them an interface to do such tasks.

Questions in regard to this
- What functionality is required/requested?
    - Adjust prize inventory
    - Adjust hours for member
    - More?
- Who should have access?
- Button/panal on the existing volunteer page or new page?

**Comment by seanbseanb** [comment]
hihi

**Comment by tskeeley** [comment]
Permissions to make changes like this would be limited to admins and the heads of the volunteer department (and, I suppose their director, but that is not critical)

I have a preference that it show on the current volunteer page - but not married to it.

Functions:
- Enter new prize/shipment receipt
- Adjust inventory
- Edit prize properties
- Adjust member hours - limited to update and deleting an hours entry.  (if they need to add time, use the form, no need to duplicate the function) - Should be able to adjust time, modifier, department, end time, and authorized by.  Should not be able to change entered by or member credited. (that should require a delete-add)
- Audit/export - A full csv list of entries in case of "other needs".  Supporting the idea of "pull the data and tell me how many people worked in both Nerf and Room Parties" or whatever.
- Reporting:
-- Who worked in x department
-- Who worked at least 30 hours (variable?)
-- How many 'unclaimed'/unrewarded hours are there

That's my first blush at it.  There will be more things as time goes on, but we need a starting place.

**Comment by cvg-it** [comment]
What’re we shipping?  Or is this for incoming inventory?

--
Sean Berry Co-Head / IT
it@convergence-con.org
414-339-1033

**Comment by AricStewart** [comment]
I believe he means incoming inventory but I do not know. Hence the question.

**Comment by AricStewart** [comment]
The only piece missing here is: Audit/export - A full csv list of entries in case of "other needs". Supporting the idea of "pull the data and tell me how many people worked in both Nerf and Room Parties" or whatever.

Some more clarification required.

**Comment by tskeeley** [comment]
sorry - dropped ball.

Shipment was reference to an idea Sean had a while ago - can we let volunteers choose their prizes and ship them?  It's not practical for us now, but might be nice in the future.

Full CSV - a merged list output of data.  at least one, likely two.  a list of all hours entries.  a list of all redemption entries.  All lookups completed.  The goal would be "hey, I want the data so I can do this CRAZY thing that no one will ever do again because I'm a special snow flake."  and this is the response, "okay, here's the raw data.  go away".  and No, no PPI, only AccountID/UUID.  if they need names/emails/etc, then they need to go through the protected data requests process.  (CVG Specif

**Comment by tskeeley** [comment]
New and interesting oddity.  I can't switch to "admin mode" on the volunteer page.  I put in my password to confirm, and it dumps me bacck to non-admin.  no error or message given.

**Comment by AricStewart** [comment]
I just confirmed here that it is working in my system

Could you look at the javascript console and see if anything is there.

**Comment by tskeeley** [comment]
weird!!!  Look at this!

[Violation] 'setTimeout' handler took 51ms - That is from onlogwff.js

**Comment by AricStewart** [comment]
onlogwff.js appears to be a lastpassword related file...  I have lastpassword installed as well but it is still working...

**Comment by tskeeley** [comment]
okay, then likely that is coincidental and an app error, not page-javascript out..  sigh.  hang on....

Here we go!!!

index.php?Function=volunteers/admin:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"w3-center w3-input w3-border w3-margin w3-padding" type=​"password" id=​"password_input" style=​"width:​ 95%;​">​

**Comment by tskeeley** [comment]
Added screencast to show

**Comment by AricStewart** [comment]
How really strange. I am on Chrome Version 64.0.3282.186 (Official Build) (64-bit) for OS/X and I do not see that behavior at all. I will investigate.

**Comment by tskeeley** [comment]
I'm on Chrome, Version 64.0.3282.140 (Official Build) (64-bit), OpenSUSE.  I can't imagine that the OS is going to get in the way of javascript.  Well, shouldn't. :)   Annoying though.  I'm leaving this one for you, javascript isn't generally my friend (ignore the AJAX I did before, in GENERAL I avoid it LOL)

I should have time this evening to look at a few things.  Here's hoping!

**Comment by AricStewart** [comment]
Ok 30 second check...

Could you change "authentication.js" line 95 of 129

from 
`      var form = document.createElement('DIV');`
to
`      var form = document.createElement('FORM');`

**Comment by AricStewart** [comment]
New Question, who can "sign" timesheets.  Right now the Volunteer Hours page only appears to concom in the volunteer department and admins.  But that is not right. It should show up to all the staff who meet requirement... X?   Head? Sub-head? I forget who you need to sign off on your blue book but I assume it would be the same.

**Comment by AricStewart** [comment]
Ok I have addressed this in pull request #84

**Comment by AricStewart** [comment]
I believe all the tasks in this issue are completed. 

I am just worried about Thomas' failure to get the volunteers page to authorize into admin mode. 

Once the authentication.js change is checked then we can close this out!
