### ISSUE TITLE
Kiosk Modes

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Signin#57]
I have been pondering over the idea of how you get computers with functionality needed for things like volunteers and eventually registration into the hands of volunteers with functionality unlocked and not required the volunteers to have to log in and be given some special permissions.

My idea is to have a kiosk mode for those computers.

So a volunteer computer can be, by a volunteer concom member, put into volunteer kiosk mode.  This will lock it down to volunteer desk related operations (volhours and volunteers) and allow admin mode but only after re-authentication.

This way you can have a designated machine unprivilaged volunteers can site behind and do the required operations for the office. 

Similarly with registration, you can have the machines setup in registration kiosk mode and it will be locked down to exactly what the volunteer behind the machine needs to do.

Thoughts?

**Comment by cvg-it** [comment]
That’s part of what we’re building the new reg user function for.  

We still want accountability for who did what, and who’s logged into a given machine.  We only use wide-open access in Neon out of necessity right now in reg.  Ideally we’d have a limited privilege role with individual accounts.

**Comment by AricStewart** [comment]
I still feel very strongly that we should not require any volunteer to have to know/remember their passwords in order to volunteer.

Now we could make it that when an ConCom member who is signing in the volunteer sets up the workstation the could sign the kiosk mode using the volunteers badge #. That way a session can be tracked to a user.

Note there is NOTHING in the database presently that tracks who is making what changes. So if you want accountability in the volunteers prize distribution that will need to be added in.

**Comment by cvg-it** [comment]
Not to volunteer, but one of the use cases discussed has been “how many volunteer hours do I have / need”

**Comment by seanbseanb** [comment]
Not in a log, nothing?

**Comment by AricStewart** [comment]
@cvg-it : Have is clearly stated on the main screen. Need is need for what? The various prizes? 

@seanbseanb : Nope, nowhere it was not in the spec @tskeeley wrote up or in the database. If that is a requirement then we should get it in.

**Comment by cvg-it** [comment]
Can you point me to the spec in question?

**Comment by AricStewart** [comment]
Look at closed issue #27 .

At then end you will see  a link to [Convergence.Events.Portal.Master.DB-v6.pdf](https://github.com/CON-In-A-Box/CIAB-Signin/files/1605935/Convergence.Events.Portal.Master.DB-v6.pdf)

Or just grab it here.
