### ISSUE TITLE
Volunteer Scheduling

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Signin#59]
Any desire from volunteers to have this as part of this system? I think it is the last at con big part of volunteers not addressed.

I can see if they have their own method to handle scheduling there could be no interest.

**Comment by seanbseanb** [comment]
They’re doing their own scheduling via google calendars, so while it’s something we -could- take on, it’s a big hill to climb, and I’m not sure it makes sense to build this functionality out immediately.

**Comment by AricStewart** [comment]
Understood. Will close this issue. If requested at a later date then it can be reopened. 

Beyond Convergence, to be a true generic con-in-a-box we will want scheduling as a component.
