### ISSUE TITLE
Track changes in Database (From Issue #57)

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Signin#64]
Should we be more close tracking who makes what change in the database? This is spawned from conversation on issue #57 . 

If such tracking is desired then it needs to be designed in.

**Comment by tskeeley** [comment]
I think any changes to the DB Schema would be linked to an issue/project and tracked that way.  No?  Or did I miss your point?

**Comment by tskeeley** [comment]
OH!  wait, this is an audit log.  Yes, that's a darn good idea.  So, not about schema, about who did what at what time.  I'll add a logs/actions table to the DB and we can update the db functions to make ongoing entries as things happen.  yes?

**Comment by AricStewart** [comment]
Exactly!

**Comment by AricStewart** [comment]
Maybe first pass this is the answer?

https://stackoverflow.com/questions/5441972/how-to-see-log-files-in-mysql?utm_medium=organic

**Comment by tskeeley** [comment]
so, in effect, you're suggestion something as simple as adding:

SET GLOBAL general_log = 'ON';
SET GLOBAL slow_query_log = 'ON';

in the DB Setup routine?

**Comment by AricStewart** [comment]
I would probably do it by  modifying /etc/mysql/my.cnf if we can. That way we have more control over where the logs go.

But we could also do it in the DB setup routine.

**Comment by tskeeley** [comment]
The problem I see is, most Hosting Providers don't allow users to modify the my.cnf file.  Ours doesn't either.  I think it would be best to do both, but the my.cnf would be a "readme.txt" suggestion.

I am willing to go your route (and put the note in the readme "if you can't change your my.sql...") if you feel strongly about it.  Let me know, and I'll make it happen.

**Comment by AricStewart** [comment]
I do not feel strongly. So just adding it to the DB setup routine would be interesting to see if it works.
Will we then have access to the resulting files?

**Comment by tskeeley** [comment]
The file will writ.....  hmmm, I was going to say it would write to our logs directory, but that's a fairly serious assumption.  Hold please...  I need time to research

**Comment by tskeeley** [comment]
Fail.  ARGH.   So, the mysql logs are written to the DB server, and we can't access them directly.  This won't work for a shared host situation.

Okay, now we are back to making a log of entries so we can access them.  BUT, I think I have a cleaner way of doing it now.  I will pick this back up and try again.
