### ISSUE TITLE
menubar undefined index

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#68]
[Thu Feb 22 04:29:01.839259 2018] [php7:notice] [pid 10588] [client ::1:56082] PHP Notice:  Undefined index: CIAB_VOLUNTEERADMIN in /home/tskeeley/Documents/Repositories/CIAB-Signin/modules/volunteers/pages/menubar.inc on line 16, referer: http://localhost/index.php?Function=profile

**Comment by AricStewart** [comment]
This should now be fixed

**Comment by tskeeley** [comment]
This one is fixed, but another that is nearly identical will happen on line 6 of /index.php if you go to the site without a function entry:

[Sun Feb 25 20:25:38.091893 2018] [php7:notice] [pid 3838] [client ::1:46014] PHP Notice:  Undefined index: Function in /home/tskeeley/Documents/Repositories/CIAB-Signin/index.php on line 6

See line 17 for the expected work around.  And, likely, we should move the functions of lines 5-9 into the Divert block as the first elseif clause (in front of "DeepLink") since that whole block is about acceptable "next step".  We should likely move lines 10-15 into the next block to catch kiosk and direct there too.  looks like the whole kitten caboodle is a redirection function, maybe! :)

Not closing since I'd just have to open a new one. :)  Go ahead and link the fix to this issue so when merged, it closes.

**Comment by tskeeley** [comment]
Woops, hit another one, and a big one:

[Sun Feb 25 20:35:14.113213 2018] [php7:warn] [pid 3840] [client ::1:46110] PHP Warning:  Use of undefined constant kioskMode - assumed 'kioskMode' (this will throw an Error in a future version of PHP) in /home/tskeeley/Documents/Repositories/CIAB-Signin/pages/base/menubar.inc on line 51, referer: http://localhost/index.php?Function=public

message flood on the logs.

**Comment by tskeeley** [comment]
(PS: these are coming from apache's error_log, if you are wondering)

**Comment by AricStewart** [comment]
AH! Ok I was wondering where you where seeing them.  I will start keeping an eye on the apache error_log also and try to clean these all up.

**Comment by tskeeley** [comment]
Thanks!  And I was the same way when someone got all on my case about "dirty code" and log flooding.  LOL  It's all good! :)

**Comment by AricStewart** [comment]
well humm,  php on my macbook is not logging to the apache logs. So I am not getting any of those messages. Trying to figure out the configuration here to make it start logging so I can see it.

**Comment by tskeeley** [comment]
check your php.ini.  There is a setting on where to send logs.

By default, it's in the php7 apache module configuration directory.  That's not helpful sincce I don't remember where I found it on my mac before.

**Comment by AricStewart** [comment]
I believe pull request #78 will fix these all up for now

**Comment by tskeeley** [comment]
Fixed.
