### ISSUE TITLE
ConCom list not showing person in multiple departments

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#75]
If I am in two departments (or more, I think there is one person in five departments), it only shows one, the first one it seems.  and it drops all the rest without notice.

Likely this is happening when the list is pulled from the DB and pushed into array.

I didn't see it before, so maybe something changed during the move to the local db instead?

Also, php is tossing an error when you try and add someone to concom but leave the "note" field blank.  figured that was just a missed check for !empty, so I didn't add it as a separate bug

**Comment by AricStewart** [comment]
This should now be resolved i believe.
