### ISSUE TITLE
Registration Guest: Authenticate using existing credentials

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#81]
As a Guest, I want to be able to authenticate to CIAB using credentials I already have.

If I have forgotten my password, I want to be able to reset it from the authentication screen.

**Comment by tskeeley** [comment]
The user already does authenticate using credentials.  All users do.  Is this like #82 but for password change/recovery without logging into neon?

**Comment by seanbseanb** [comment]
How will we authenticate post-neon?  The idea here is to use another authentication system so that we can work without neon.  Can we rough in some auth tables and setup our own authentication?

**Comment by AricStewart** [comment]
I have implemented a basic User/Password login. the Username(or email) stays the same from Neon days but the user will need to reset their password.

Or if we have some overlap time we could fake populate the database by checking a given password vs Neon and populating our password file on success.

**Comment by AricStewart** [comment]
This has been in place since 2018.
