### ISSUE TITLE
Registration Backend: Sync Events Database Content to CIAB

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#85]
In aid of us eventually moving away from using the NeonCRM Events database, we want to be able to periodically dump the NeonCRM Events database into tables in CIAB.

Tasks on this include:
1. Extract a sample of the Events DB (Aric, done?)
2. Design tables for the data to go into CIAB (SB, TSK)
3. Build out the tables (?)
4. Build the process to do it (Aric)
5. Validation

**Comment by tskeeley** [comment]
This is kinda an overview of the reg backend project already created.   But we'll use this for the specific sync process tracking.  At least, I think that was your goal here.

**Comment by AricStewart** [comment]
Making pretty good progress on this. Hitting some rough corners and gaps in the Neon REST api but we should be able to have something serviceable. 

I would likely think it should run as a crontab or something. So we will want to document how to set that up

**Comment by AricStewart** [comment]
- [x] Extract a sample of the Events DB (Aric, done?)
- [x] Design tables for the data to go into CIAB (SB, TSK)
- [x] Build out the tables (?)
- [x] Build the process to do it (Aric)

As of PullRequest #89 

- [ ] Validation

How do we want it validated?

- [ ] Build the chron mechanism to run this regularly

**Comment by AricStewart** [comment]
validation: just something to prove that it worked and we maybe got as many records as we expected

**Comment by AricStewart** [comment]
This is finished I believe. 

There is not easy way to mark as fixed or assign back to Sean to confirm so I am going to close this and if people disagree we can reopen it.
