### ISSUE TITLE
Merge Year data with event data

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Signin#88]
Merge Year data into event data to avoid duplicated data efforts

**Comment by tskeeley** [comment]
Add datestart, dateend to events

Add availablefrom, availableto to BadgeTypes

Add table DBPullPage, fields NEON:AttendeeID/DB.registrations.registrationID, NEON.Page - to be used to support "force update" of individual event records on demand of the user:
-- I've made a change to my .... (eg: badgename) and I want to see that it took/ready it for printing

**Comment by AricStewart** [comment]
Also Important thing.  We need the Registrations. BadgeName to be able to handle non latin characters. For example this is a currently registered badge 'Q(t)/π'

Setting the string encoding to utf8_unicode_ci works.

**Comment by AricStewart** [comment]
Another possible database change/question...

last year we had a badge with the badge name "Captain Saffron, Captain of Serenity, His Brownshirtness, Commander Of Scallywags, Assistant Walker to Her Majesty, Jetta von Puff and His Wiggliness, Mr. Petey, Slayer of Dragons, Defender of the Faith, He Who Tastes The Scotches, and Soforth"

If you quickly count (or trust me) that is 245 characters long. Registrations->BadgeName has a limit of 100 characters.

what do we do?

**Comment by AricStewart** [comment]
Finally to have all outstanding database issues around events that Thomas and I talked about in one place... We talked about storing the page a given `Registrations` entry is found on. I believe the idea was that have a supplementary table that used the `Registrations` . `RegistrationID` as the key to index the data. 

The goal is for when this data is no longer needed as a holdover from Neon we can just drop the table and there are no issues.

**Comment by tskeeley** [comment]
OH!!!   YES.  I did do that, but I never pushed it because we got
sidetracked with events not pulling a ticket-id.  Okay, I'll dig it up,
finish it and push it out before the weekend.  Thanks for the reminder and
sorry I dropped it.


-- Thomas Keeley

If a Smurf holds its breath for too long, what color does it turn??
Para. Jeff Dunham
