### ISSUE TITLE
Enter Hours Page: Volunteer Badge #, Email or Full Name Field: Preferred Name Search

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#93]
Enhancement: Currently need to search by legal full name (first and last) ADD/CHANGE ability to search by preferred name.

**Comment by AricStewart** [comment]
Currently you can search by badge #, Legal full name, email address, and with next update badge name.
I can add preferred name also.

**Comment by AricStewart** [comment]
Please retest with new release, re-open if failure remains.

**Comment by lmhern1** [comment]
When searching using a Preferred First name and Legal Last Name, no member is found. 

Examples: Talie Keeley
                   Liz Hernandez

**Comment by AricStewart** [comment]
Ok this is more complicated than I thought.  There is a preferred first and preferred last isn;t there and I have to handle one or the other or both being set.  Thanks for the examples to test with.

Right now if both are set and you use both they should search correctly.

**Comment by AricStewart** [comment]
Ok this has been fixed again. Please retest.
