### ISSUE TITLE
Enter Hours Page: Volunteer Badge #, Email or Full Name Field: Error Message-Member Not Found

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#94]
Enhancement: Add an error message when member is not found. (Currently there is an invalid lookup message that appears when only a first or last name is entered.)

**Comment by AricStewart** [comment]
What page?

There are few number of pages where this lookup is used, Right now Volunteer hours and Volunteer admin.  I can work to improve the error reporting.

**Comment by lmhern1** [comment]
This was noted on the Enter Hours Page (Volunteer Hours page, but having an error message in the Volunteer admin page would also be useful/wanted.

**Comment by AricStewart** [comment]
Ok I will take the note to try to improve it in general.

**Comment by AricStewart** [comment]
Should be fixed, reopen if not.
