### ISSUE TITLE
Profile Page: Add Account ID

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#95]
Enhancement: ADD account ID to the Profile page (user would have the ability to look up their own account ID and communicate it to the departments as needed. This will allow departments to find volunteers and log hours more quickly and efficiently.)

**Comment by AricStewart** [comment]
Humm I just submitted it as badge number not account ID, should I change it.

**Comment by lmhern1** [comment]
So, hopefully not speaking out of turn, but my understanding was that the Account ID would be the badge number for this year. So, assuming you generated the Badge Number field with the Account ID Number, then that will work just fine!

**Comment by AricStewart** [comment]
Yes it is the account id I just labeled it badge number because I too am under the understanding that they will be on in the same this coming year.

**Comment by AricStewart** [comment]
Please retest with new release, re-open if failure remains.
