### ISSUE TITLE
Volunteers Page: Kiosk Mode: Login of New User

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#98]
Enhancement: In Kiosk Mode: ADD login of new user? Currently it appears that the ID associated with actions done in the Kiosk Mode will be the ID of the person who initially logged into the device. For reference, in kiosk mode, who's account/ID number is logged in the "Entered By" field?

**Comment by AricStewart** [comment]
The tricky thing here is that it would then require all volunteers at the console to remember their password. 

Either that or we have an 'operated by' sort of selection box that would just accept a badge number/name/etc... and use that without question.

**Comment by AricStewart** [comment]
Accepted
